sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - 'lts/*'
script:
  - npm run lint
  - npm run build
#  - npm run test
# before_script:
#   - "sudo chown root /opt/google/chrome/chrome-sandbox"
#   - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - sleep 3 # give xvfb some time to start
